jdbcSettings:
 url: "jdbc:mysql://localhost:3306/simpsons?useSSL=false&serverTimezone=UTC"
 username: "root"
 password: "@livger8"
 driverClassName: "com.mysql.cj.jdbc.Driver"


packageName: "edu.mum.cs544"